# -*- coding: utf-8 -*-
"""Astro-gen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14PcExq0X4WD_ARvdKqlppFVlYwd9s8-g

# H-R Diagram

# ***Methodology and Working Principle of the Automated H-R Diagram Generator Introduction** The **Hertzsprung–Russell (H-R) Diagram** is one of the most fundamental tools in astronomy for studying the properties and evolution of stars. Traditionally, constructing an H-R diagram requires downloading astronomical catalogs, cleaning the data, performing multiple mathematical calculations, and finally plotting the graph. These steps are time-consuming and prone to human error when done manually. To overcome these limitations, this project adopts a smart work methodology by automating the entire workflow using Python, the Gaia DR3 astronomical database, and scientific computing libraries. Instead of manually collecting and processing stellar data, the program performs all tasks automatically, producing a scientifically accurate H-R diagram within a few seconds
"""

import numpy as np
import matplotlib.pyplot as plt
import sys

# --- Import astroquery for Gaia data access ---
# This block attempts to import the Gaia module from astroquery.
# If astroquery is not installed, it provides instructions to install it
# and creates a stub class to gracefully handle its absence.
try:
    from astroquery.gaia import Gaia
except ImportError:
    print("""astroquery is not installed. Install it with 'pip install astroquery' to
enable Gaia queries.""")
    class Gaia:
        """Stub Gaia class that mimics the minimal interface used in this script.
        Calling launch_job_async will raise ImportError with guidance.
        """
        @staticmethod
        def launch_job_async(*args, **kwargs):
            raise ImportError(
                """astroquery is not installed. Install it with 'pip install astroquery' to query the
Gaia archive."""
            )

print("Connecting directly to the live ESA Gaia Archive via web API...")

# --- Define the Gaia Astronomical Query ---
# This SQL-like query selects specific columns from the Gaia DR3 catalog.
# - TOP 100000000: Limits the number of results for performance.
# - phot_g_mean_mag: G-band mean magnitude (apparent magnitude).
# - bp_rp: Blue-Photometer minus Red-Photometer color index (temperature proxy).
# - parallax: Parallax in milliarcseconds (distance proxy).
# - WHERE clauses: Filters out rows with missing data and applies quality cuts.
#   - parallax > 10: Ensures stars are relatively close (within ~100 parsecs).
#   - parallax_over_error > 25: A strict quality filter for reliable parallax measurements.
gaia_query = """
SELECT TOP 100000000
    phot_g_mean_mag, bp_rp, parallax
FROM gaiadr3.gaia_source
WHERE bp_rp IS NOT NULL
AND phot_g_mean_mag IS NOT NULL
AND parallax > 10 -- Keeps stars within ~100 parsecs for clean math
AND parallax_over_error > 25 -- Strict quality filter for reliability
"""

# --- Execute the Query and Process Data ---
# This block attempts to run the Gaia query and process the results.
# It includes error handling for cases where the Gaia server might be unavailable or busy.
try:
    # Launch the asynchronous job to query the Gaia archive
    job = Gaia.launch_job_async(gaia_query)
    # Get the results from the job, which is a FITS table-like object
    star_table = job.get_results()
    print(f"■ Success! Loaded data for {len(star_table)} stars straight into memory.")

    # Extract relevant columns from the star_table
    apparent_mag = star_table['phot_g_mean_mag']  # G-band apparent magnitude
    color_index = star_table['bp_rp']            # Color index (BP-RP)
    parallax_arcsec = star_table['parallax'] / 1000.0 # Convert parallax from milliarcseconds to arcseconds

    # --- Calculate Absolute Magnitude ---
    # The absolute magnitude (M) is derived from the apparent magnitude (m) and parallax (p)
    # using the formula: M = m + 5 + 5 * log10(p).
    absolute_mag = apparent_mag + 5 + 5 * np.log10(parallax_arcsec)

    # --- Calculate Derived Luminosity ---
    # Luminosity (L) relative to the Sun's luminosity (L_sun) is derived from absolute magnitude.
    # The Sun's absolute G-band magnitude is approximately 4.77.
    # The formula is: L / L_sun = 10^((M_sun - M) / 2.5)
    derived_luminosity = 10**((4.77 - absolute_mag) / 2.5)

    # --- Plotting the Hertzsprung-Russell (H-R) Diagram ---
    # An H-R diagram plots stellar luminosity against stellar temperature (color index).
    plt.style.use('dark_background') # Set a dark background for the plot for better contrast
    fig, ax_left = plt.subplots(figsize=(10, 9)) # Create a figure and a primary axes object

    # Scatter plot of color index vs. derived luminosity
    # - c: Color of points based on absolute magnitude
    # - cmap: Colormap for absolute magnitude (plasma_r is reversed plasma)
    # - s: Size of markers
    # - alpha: Transparency of markers
    # - edgecolors: No edges for markers
    star_plot = ax_left.scatter(
        color_index, derived_luminosity,
        c=absolute_mag, cmap='plasma_r',
        s=6, alpha=0.7, edgecolors='none'
    )

    # --- Configure Primary Y-axis (Luminosity) ---
    ax_left.set_yscale('log') # Set y-axis to logarithmic scale for luminosity
    ax_left.set_xlabel("Temperture (Kelvin) ($G_{BP} - G_{RP}$)", fontsize=12,
                       labelpad=10) # X-axis label: Color index as a proxy for temperature
    ax_left.set_ylabel(r"Luminosity ($L / L_{\odot}$)", fontsize=12, color='cyan',
                       fontweight='bold') # Left Y-axis label: Luminosity relative to Sun
    ax_left.tick_params(axis='y', labelcolor='cyan') # Set tick color for left Y-axis

    # --- Configure X-axis and Luminosity Y-axis Limits ---
    ax_left.set_xlim(-0.5, 3.5) # Set limits for the X-axis (color index)
    ax_left.set_ylim(1e-4, 1e5)  # Set limits for the left Y-axis (luminosity)

    # --- Create a Secondary Y-axis (Absolute Magnitude) ---
    # This allows plotting absolute magnitude on the right side, which is inversely related to luminosity.
    ax_right = ax_left.twinx() # Create a twin axes sharing the same x-axis
    ax_right.set_ylim(16, -6)  # Set limits for the right Y-axis (absolute magnitude)
    ax_right.set_ylabel("Absolute Magnitude ($M_G$)", fontsize=12, color='magenta',
                        fontweight='bold', labelpad=15) # Right Y-axis label
    ax_right.tick_params(axis='y', labelcolor='magenta') # Set tick color for right Y-axis

    # --- Add Annotations for Stellar Regions ---
    # Text annotations to label key regions of the H-R diagram (Main Sequence, Red Giants, White Dwarfs).
    ax_left.text(0.5, 5, "Main Sequence \u2192", color='white', fontsize=11, alpha=0.8,
                 rotation=-45) # Main Sequence label
    ax_left.text(1.8, 500, "Red Giants", color='Red', fontsize=11, fontweight='bold') # Red Giants label
    ax_left.text(0.0, 0.0003, "White Dwarfs", color='Navy blue', fontsize=11,
                 fontweight='bold') # White Dwarfs label

    # --- Final Plot Configuration ---
    plt.title(("H-R Diagram"), fontsize=14, pad=20) # Set the title of the plot
    plt.tight_layout() # Adjust plot to ensure everything fits without overlapping
    plt.show() # Display the generated plot

# --- Error Handling for Gaia Query ---
# Catches exceptions during the query process and provides user-friendly guidance.
except Exception as e:
    print("\n■ The Gaia server rejected the query or timed out again.")
    print("""Please wait 1-2 minutes and re-run this cell. The ESA servers are temporarily
overloaded.""")
import numpy as np
import matplotlib.pyplot as plt
import sys

# --- Import astroquery for Gaia data access ---
# This block attempts to import the Gaia module from astroquery.
# If astroquery is not installed, it provides instructions to install it
# and creates a stub class to gracefully handle its absence.
try:
    from astroquery.gaia import Gaia
except ImportError:
    print("""astroquery is not installed. Install it with 'pip install astroquery' to
enable Gaia queries.""")
    class Gaia:
        """Stub Gaia class that mimics the minimal interface used in this script.
        Calling launch_job_async will raise ImportError with guidance.
        """
        @staticmethod
        def launch_job_async(*args, **kwargs):
            raise ImportError(
                """astroquery is not installed. Install it with 'pip install astroquery' to query the
Gaia archive."""
            )

print("Connecting directly to the live ESA Gaia Archive via web API...")

# --- Define the Gaia Astronomical Query ---
# This SQL-like query selects specific columns from the Gaia DR3 catalog.
# - TOP 100000000: Limits the number of results for performance.
# - phot_g_mean_mag: G-band mean magnitude (apparent magnitude).
# - bp_rp: Blue-Photometer minus Red-Photometer color index (temperature proxy).
# - parallax: Parallax in milliarcseconds (distance proxy).
# - WHERE clauses: Filters out rows with missing data and applies quality cuts.
#   - parallax > 10: Ensures stars are relatively close (within ~100 parsecs).
#   - parallax_over_error > 25: A strict quality filter for reliable parallax measurements.
gaia_query = """
SELECT TOP 100000000
    phot_g_mean_mag, bp_rp, parallax
FROM gaiadr3.gaia_source
WHERE bp_rp IS NOT NULL
AND phot_g_mean_mag IS NOT NULL
AND parallax > 10 -- Keeps stars within ~100 parsecs for clean math
AND parallax_over_error > 25 -- Strict quality filter for reliability
"""

# --- Execute the Query and Process Data ---
# This block attempts to run the Gaia query and process the results.
# It includes error handling for cases where the Gaia server might be unavailable or busy.
try:
    # Launch the asynchronous job to query the Gaia archive
    job = Gaia.launch_job_async(gaia_query)
    # Get the results from the job, which is a FITS table-like object
    star_table = job.get_results()
    print(f"■ Success! Loaded data for {len(star_table)} stars straight into memory.")

    # Extract relevant columns from the star_table
    apparent_mag = star_table['phot_g_mean_mag']  # G-band apparent magnitude
    color_index = star_table['bp_rp']            # Color index (BP-RP)
    parallax_arcsec = star_table['parallax'] / 1000.0 # Convert parallax from milliarcseconds to arcseconds

    # --- Calculate Absolute Magnitude ---
    # The absolute magnitude (M) is derived from the apparent magnitude (m) and parallax (p)
    # using the formula: M = m + 5 + 5 * log10(p).
    absolute_mag = apparent_mag + 5 + 5 * np.log10(parallax_arcsec)

    # --- Calculate Derived Luminosity ---
    # Luminosity (L) relative to the Sun's luminosity (L_sun) is derived from absolute magnitude.
    # The Sun's absolute G-band magnitude is approximately 4.77.
    # The formula is: L / L_sun = 10^((M_sun - M) / 2.5)
    derived_luminosity = 10**((4.77 - absolute_mag) / 2.5)

    # --- Plotting the Hertzsprung-Russell (H-R) Diagram ---
    # An H-R diagram plots stellar luminosity against stellar temperature (color index).
    plt.style.use('dark_background') # Set a dark background for the plot for better contrast
    fig, ax_left = plt.subplots(figsize=(10, 9)) # Create a figure and a primary axes object

    # Scatter plot of color index vs. derived luminosity
    # - c: Color of points based on absolute magnitude
    # - cmap: Colormap for absolute magnitude (plasma_r is reversed plasma)
    # - s: Size of markers
    # - alpha: Transparency of markers
    # - edgecolors: No edges for markers
    star_plot = ax_left.scatter(
        color_index, derived_luminosity,
        c=absolute_mag, cmap='plasma_r',
        s=6, alpha=0.7, edgecolors='none'
    )

    # --- Configure Primary Y-axis (Luminosity) ---
    ax_left.set_yscale('log') # Set y-axis to logarithmic scale for luminosity
    ax_left.set_xlabel("Temperture (Kelvin) ($G_{BP} - G_{RP}$)", fontsize=12,
                       labelpad=10) # X-axis label: Color index as a proxy for temperature
    ax_left.set_ylabel(r"Luminosity ($L / L_{\odot}$)", fontsize=12, color='cyan',
                       fontweight='bold') # Left Y-axis label: Luminosity relative to Sun
    ax_left.tick_params(axis='y', labelcolor='cyan') # Set tick color for left Y-axis

    # --- Configure X-axis and Luminosity Y-axis Limits ---
    ax_left.set_xlim(-0.5, 3.5) # Set limits for the X-axis (color index)
    ax_left.set_ylim(1e-4, 1e5)  # Set limits for the left Y-axis (luminosity)

    # --- Create a Secondary Y-axis (Absolute Magnitude) ---
    # This allows plotting absolute magnitude on the right side, which is inversely related to luminosity.
    ax_right = ax_left.twinx() # Create a twin axes sharing the same x-axis
    ax_right.set_ylim(16, -6)  # Set limits for the right Y-axis (absolute magnitude)
    ax_right.set_ylabel("Absolute Magnitude ($M_G$)", fontsize=12, color='magenta',
                        fontweight='bold', labelpad=15) # Right Y-axis label
    ax_right.tick_params(axis='y', labelcolor='magenta') # Set tick color for right Y-axis

    # --- Add Annotations for Stellar Regions ---
    # Text annotations to label key regions of the H-R diagram (Main Sequence, Red Giants, White Dwarfs).
    ax_left.text(0.5, 5, "Main Sequence \u2192", color='white', fontsize=11, alpha=0.8,
                 rotation=-45) # Main Sequence label
    ax_left.text(1.8, 500, "Red Giants", color='Red', fontsize=11, fontweight='bold') # Red Giants label
    ax_left.text(0.0, 0.0003, "White Dwarfs", color='Navy blue', fontsize=11,
                 fontweight='bold') # White Dwarfs label

    # --- Final Plot Configuration ---
    plt.title(("H-R Diagram"), fontsize=14, pad=20) # Set the title of the plot
    plt.tight_layout() # Adjust plot to ensure everything fits without overlapping
    plt.show() # Display the generated plot

# --- Error Handling for Gaia Query ---
# Catches exceptions during the query process and provides user-friendly guidance.
except Exception as e:
    print("\n■ The Gaia server rejected the query or timed out again.")
    print("""Please wait 1-2 minutes and re-run this cell. The ESA servers are temporarily
overloaded.""")

pip install astroquery